# Generated by Django 3.0.4 on 2020-03-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('a', models.AutoField(primary_key=True, serialize=False)),
                ('l1', models.CharField(max_length=200)),
                ('l2', models.CharField(max_length=200)),
                ('l3', models.CharField(max_length=200)),
                ('l4', models.CharField(max_length=200)),
                ('l5', models.CharField(max_length=200)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tsite.Student')),
            ],
        ),
    ]
