# Generated by Django 3.0.4 on 2020-03-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tsite', '0002_answers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
    ]
