# Generated by Django 3.0.4 on 2020-04-04 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tsite', '0003_auto_20200403_0351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Submissions',
        ),
    ]
