# Generated by Django 3.0.4 on 2020-03-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tsite', '0003_auto_20200327_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='name',
        ),
    ]
