# Generated by Django 3.0.4 on 2020-04-04 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tsite', '0004_auto_20200405_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{10}$')]),
        ),
    ]
