# Generated by Django 3.0.4 on 2020-03-27 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tsite', '0004_remove_answer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Tsite.Student'),
        ),
    ]
