# Generated by Django 3.0.4 on 2020-04-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tsite', '0005_auto_20200405_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersKey',
            fields=[
                ('a', models.AutoField(primary_key=True, serialize=False)),
                ('lvl_1', models.CharField(max_length=200)),
                ('lvl_2', models.CharField(max_length=200)),
                ('lvl_3', models.CharField(max_length=200)),
                ('lvl_4', models.CharField(max_length=200)),
            ],
        ),
    ]
