# Generated by Django 3.0.4 on 2020-04-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tsite', '0006_answerskey'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerskey',
            name='lvl_5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='answerskey',
            name='lvl_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='answerskey',
            name='lvl_2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='answerskey',
            name='lvl_3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='answerskey',
            name='lvl_4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
