# Generated by Django 3.0.4 on 2020-03-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tsite', '0007_auto_20200327_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='l1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='l2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='l3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='l4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='l5',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
