# Generated by Django 3.0.4 on 2020-04-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tsite', '0009_auto_20200413_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissions',
            name='l4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
